// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "@/providers/theme-provider";
// import Navbar from "@/components/common/Navbar";
// import Footer from "@/components/common/Footer";


// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "DSA Learning Platform",
//   description: "Practice DSA like LeetCode with curated problems.",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className={inter.className}>
//         <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
//           <Navbar />
//           <main className="min-h-screen">
//             {children}
//           </main>
//           <Footer />
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }


"use client"; // এটি যোগ করতে হবে কারণ আমরা ইউআরএল চেক করব

import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  
  // চেক করছি ইউআরএল কি /admin দিয়ে শুরু হয়েছে কি না
  const isAdminPage = pathname.startsWith("/admin");

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          
          {/* যদি অ্যাডমিন পেজ না হয়, তবেই ন্যাভবার দেখাবে */}
          {!isAdminPage && <Navbar />}
          
          <main className="min-h-screen">
            {children}
          </main>
          
          {/* যদি অ্যাডমিন পেজ না হয়, তবেই ফুটার দেখাবে */}
          {!isAdminPage && <Footer />}
          
        </ThemeProvider>
      </body>
    </html>
  );
}
